#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.log"
PID_FILE="${TRIM_PKGVAR}/${TRIM_APPNAME}.pid"

APP_NAME=plexmediaserver
APP_DIR=/var/apps/$APP_NAME/target
APP_DATA_DIR=/var/apps/$APP_NAME/var

SERVICE_COMMAND="$APP_DIR/bin/plex-server $APP_DATA_DIR"
SVC_BACKGROUND=y
SVC_WRITE_PID=y
